Repository voxpupuli/hiera-eyaml-gpg, pull requests merged in 2019-04, with the labels that each got.

#49 Add badges to README
  README.md
Labels: docs

#52 Simplify authors/contributors
  README.md
Labels: docs

#51 Document usage with Hiera 5
  README.md
Labels: docs

#53 Document installation of gems on puppetserver
  README.md
Labels: docs

#46 Allow gnupghome to be set from an environment variable
  README.md
  lib/hiera/backend/eyaml/encryptors/gpg.rb
Labels: enhancement, needs-tests

#38 Make the list of keys to encrypt with accurate
  lib/hiera/backend/eyaml/encryptors/gpg.rb
Labels: needs-tests

#55 Fix `uninitialized constant Puppet (NameError)`
  hiera-eyaml-gpg.gemspec
  lib/hiera/backend/eyaml/encryptors/gpg/puppet_gpg.rb
Labels: bug

#50 Document which versions of Puppet this should work with
  README.md
Labels: docs

#58 Expose plugin version
  lib/hiera/backend/eyaml/encryptors/gpg.rb
Labels: enhancement

#60 Release 0.7.0
  .travis.yml
  CHANGELOG.md
  HISTORY.md
  Rakefile
  lib/hiera/backend/eyaml/encryptors/gpg/version.rb
Labels: skip-changelog

#62 Release 0.7.1
  CHANGELOG.md
  lib/hiera/backend/eyaml/encryptors/gpg/version.rb
Labels: skip-changelog

#63 Remove gem dependency on `puppet`
  hiera-eyaml-gpg.gemspec
Labels: bug

#64 Release 0.7.2
  CHANGELOG.md
  lib/hiera/backend/eyaml/encryptors/gpg/version.rb
Labels: skip-changelog

#65 Fix uninitialized constant `Hiera::Backend::Eyaml::Encryptors::GpgVer…
  lib/hiera/backend/eyaml/encryptors/gpg.rb
Labels: bug

#66 Release 0.7.3
  CHANGELOG.md
  lib/hiera/backend/eyaml/encryptors/gpg/version.rb
Labels: skip-changelog
